In [1]:
#Import Every module you need
import pandas as pd
import numpy as np
import matplotlib as plt
import openpyxl
from datetime import datetime
from openpyxl import load_workbook
from babel.numbers import format_currency

In [2]:
#ITems to update
# MAKE SURE THE ARR & INV ARR IS RECENTLY UPDATED, then download
#DOWNLOAD IC220
#DOWNLOAD PO USAGE
#Download shortages
#Download CONVERSIONS
#DOWNLOAD DISCO
#DOWNLOAD MEDLINE SKU




#THIS  MUST GET UPDATED-----------------------------------------------------
#Get the Excel files needed, Note they must be saved as XLSX for the pd.read to work
#ARR report
Par_Report = pd.read_excel (r'N:\Supply Chain\Distribution\Demand Planning\SC Par Details Report\SC PAR Details Report2022-09-19.xlsx')
#Medline SKU Extract report
MD = pd.read_excel (r'N:\Supply Chain\Distribution\Demand Planning\Report Team\Medline SKU Extract\Medline SKU Extract.xlsx',sheet_name='Sheet1')
#Lawson UOM conversions report
UC1 = pd.read_excel (r'N:\Supply Chain\Distribution\Demand Planning\Reference Files\Lawson_UOM_Conversions_6_21_22.xlsx')
#ARR INV ARR Report
INV = pd.read_excel (r'N:\Supply Chain\Distribution\Demand Planning\SC Par Details Report\Archive\SHC-VC Asset ARR - 6.20.22.xlsx', sheet_name='IC211 (36)')
#IC220 INV Reports
INV_orders=pd.read_excel(r'N:\Supply Chain\Distribution\Demand Planning\Report Team\Build\Optimization Reports\ANES 500P\IC220 - 2022-09-19T102212.641.xlsx')
# Disco Report
DISCO=pd.read_excel(r'N:\Supply Chain\Distribution\Demand Planning\Report Team\Build\Reports\Valleycare AdHOC\Copy of Discontinuation Tracker 8-19-22.xlsx',sheet_name='Discontinued prior weeks-month')

# Medline ETA Report
ETA=pd.read_excel(r'N:\Supply Chain\Distribution\Demand Planning\Report Team\Build\Optimization Reports\ANES 500P\Medline ETA.xlsx')
# Medline Fill/Kill DED report( needs to be updated)
DED=pd.read_excel(r'N:\Supply Chain\Distribution\Demand Planning\Report Team\Build\Reports\Dialysis WorkRoom\Copy of 08-29-2022 Fill-Kill DED. Open Order and Rejection Reports.xlsx',sheet_name='DED REPORT')
# Conversion
Cost=pd.read_excel(r'N:\Supply Chain\Distribution\Demand Planning\Reference Files\Item Master Cost Details.xlsx')
#PO1 = pd.read_excel (r'N:\Supply Chain\Distribution\Demand Planning\Report Team\Build\Reports\LPCH OR\LP_PO_LINES_BY_DATE_DTLS_28865.xlsx', header=[1,0])
PO1 = pd.read_excel (r'N:\Supply Chain\Distribution\Demand Planning\Report Team\Build\Optimization Reports\ANES 500P\Supply_Chain_Procurement_-_Details (22).xlsx', sheet_name='Details')

#Item_Cost

PO1.head()

C:\Users\s0286524\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,PO Date,PO NBR,Unnamed: 2,Line,Item,Description,Vendor Reference #,Order QTY,Open QTY,Received QTY,...,UOM,Ship To,Deliver To ID,Deliver To,Accounting Unit Code,Cost Center,Cost Code,Manuf. Item (If Available),Vendor,Item Type
0,2022-03-27,27142312,NaN,1,71452,SOLUTION HI-LO GLUCOSE CONTROL,71452,6,0,6,...,BX,820Q - DS_300P GF_RECEIVING,S5023,S5023 - PS_500P 2F_K251_ANES KB S5023,74501,ANESTHESIA,Last Cost,80139,28709-ABBOTT DIABETES CARE SALES COR,NON-STOCK
1,2022-03-27,27142314,NaN,1,230215,SEVOFLURANE,1001965164,2,0,2,...,PK,820Q - DS_300P GF_RECEIVING,S5023,S5023 - PS_500P 2F_K251_ANES KB S5023,74501,ANESTHESIA,Last Cost,1001965164,10738-BAXTER HEALTHCARE CORP,NON-STOCK
2,2022-03-27,27142315,NaN,1,208836,SET SPIKE AND RESEVOIR BELMONT,903-00032,1,0,1,...,BX,820Q - DS_300P GF_RECEIVING,S5023,S5023 - PS_500P 2F_K251_ANES KB S5023,74501,ANESTHESIA,Last Cost,903-00032,10791-BELMONT INSTRUMENT LLC,NON-STOCK
3,2022-03-27,27142316,NaN,1,26780,TOOL DEFIB DOUGHNUT MAGNET CV,6860,10,0,10,...,EA,820Q - DS_300P GF_RECEIVING,S5023,S5023 - PS_500P 2F_K251_ANES KB S5023,74501,ANESTHESIA,Last Cost,6860,10905-BOSTON SCIENTIFIC CORP,NON-STOCK
4,2022-03-27,27142317,NaN,1,192650,GDE NDL ACCUSITE ST CIV-FLEX,610-1017,1,0,1,...,BX,820Q - DS_300P GF_RECEIVING,S5023,S5023 - PS_500P 2F_K251_ANES KB S5023,74501,ANESTHESIA,Entered,610-1017,11290-CIVCO MEDICAL INSTRUMENTS,NON-STOCK

# Create the excel sheet

In [3]:
#Create Excel Sheet
File_name1="N:\Supply Chain\Distribution\Demand Planning\Report Team\Build\Optimization Reports\Anesthesia.xlsx"

# Par Details/PO Details/Inventory- Input Par Locations

In [4]:
Par_Report.dtypes

ENTITY                   object
LOCATION                 object
LOCATION NAME            object
ITEM                      int64
ITEM DESCRIPTION         object
PAR LEVEL                 int64
UOM                      object
CONV UOM                float64
MANUF NAME               object
MANUF_NBR                object
VENDOR                  float64
VENDOR CATALOG           object
COST CTR                float64
Concat Lawson-CC         object
PREFER_BIN               object
PAR IDs                  object
Division                 object
CLINICAL DESCRIPTION     object
COLOR CATEGORY           object
REPL_FROM_CO            float64
REPL_FROM_LOC            object
dtype: object

In [5]:
#THIS NEEDS TO BE UPDATED
#Drop the columns that are not needed
Par_R=Par_Report.drop(columns=['PAR IDs','COLOR CATEGORY'])


#Filter the Locations needed for the Optimization report, Input par locations as needed

CHECK = Par_R[(Par_R["LOCATION"]=="S5023")]
#|(Par_Report["LOCATION"]=="6171A")|(Par_Report["LOCATION"]=="6172A")]


CHECK

,ENTITY,LOCATION,LOCATION NAME,ITEM,ITEM DESCRIPTION,PAR LEVEL,UOM,CONV UOM,MANUF NAME,MANUF_NBR,VENDOR,VENDOR CATALOG,COST CTR,Concat Lawson-CC,PREFER_BIN,Division,CLINICAL DESCRIPTION,REPL_FROM_CO,REPL_FROM_LOC
131131,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010,NDL EPIDUR 17GA 5CM STIMUCATH,20,EA,1.0,TELEFLEX LLC,AB-00050,13385.0,AB-00050,74501.0,100010-74501,D440S2,Procedural,NEEDLE BLOCK 17G,0.0,NaN
131132,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012,NDL EPIDUR 17GA 15CM STIMUCATH,5,EA,1.0,TELEFLEX LLC,AB-00150,13385.0,AB-00150,74501.0,100012-74501,D445S2,Procedural,NaN,0.0,NaN
131133,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397,PACK COBAN LF WRAP BRIGHTS,2,EA,1.0,3M HEALTHCARE,2082C,13385.0,MMM2082C,74501.0,100397-74501,H165S2,Procedural,"COBAN 2""",0.0,NaN
131134,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136,TAPE DRSG MEPITAC 118X.75IN,2,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,13385.0,SCP298300,74501.0,101136-74501,H140S2,Procedural,MEPITAC TAPE,0.0,NaN
131135,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879,NDLE HYPO 27GA 1/2IN STRL,1,BX,100.0,BECTON DICKINSON,305109,13385.0,B-D305109,74501.0,101879-74501,G035S2,Procedural,NEEDLE HYPO 27Gx0.5,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131667,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97389,ELCTRD ECG SQ RDLUCNT 24IN,2,PK,3.0,CARDINAL HEALTH,31424785,13385.0,LTP31424785,74501.0,97389-74501,P535S2,Procedural,PUPPY DOG LEADS,0.0,NaN
131668,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97737,TUBE TRCH TAPERGUARD EVAC SZ 7,10,EA,1.0,"COVIDIEN, LTD.",18870,13385.0,18870,74501.0,97737-74501,CAB5C03,Procedural,TUBE ET TAPER EVAC 7.0,0.0,NaN
131669,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97738,TUBE TRCHL TPR GARD 7.5MM,10,EA,1.0,"COVIDIEN, LTD.",18875,13385.0,18875,74501.0,97738-74501,CAB5D01,Procedural,TUBE ET TAPER EVAC 7.5,0.0,NaN
131670,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97739,TUBE TRCHL TPR GARD 8X11.8MM,10,EA,1.0,"COVIDIEN, LTD.",18880,13385.0,18880,74501.0,97739-74501,CAB5D02,Procedural,TUBE ET TAPER EVAC 8.0,0.0,NaN
131671,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97765,SET FLTRLN H HUMIDIFIED ADLT,3,EA,1.0,PHILIPS HEALTHCARE,989803105541,13385.0,HWPM1921A,74501.0,97765-74501,M405S2,Procedural,H SET FILTERLINE ADULT,0.0,NaN

In [6]:
#Filter the INVENTORY for the COST CENTER
INV_Check=INV_orders[(INV_orders["ICT-FROM-TO-LOC"]=="S5023")]
#|(INV_orders["ICT-FROM-TO-LOC"]=="6171A")|(INV_orders["ICT-FROM-TO-LOC"]=="6172A")]
INV_Check.head()

,ICT-COMPANY,ICC-NAME,Currency Code,SORT-LITERAL,FR-UPDATE-DATE,TO-UPDATE-DATE,ICT-ITEM,ITE-DESCRIPTION,ITE-DESCRIPTION2,ICT-LOCATION,...,TO-UPDATE-DATE-2,ICT-LOCATION-2,ICL-NAME-2,ICT-RECEIPT-TOTAL-2,ICT-ISSUE-TOTAL-2,ICT-ADJIN-TOTAL-2,ICT-ADJOUT-TOTAL-2,ICT-TRANSFER-TOTAL-2,ICT-PHY-INV-TOTAL-2,ICT-REQ-RET-TOTAL-2
0,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,101884,NDL HYPODERMC 18GA 1.5IN,NaN,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,101884,NDL HYPODERMC 18GA 1.5IN,NaN,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,101884,NDL HYPODERMC 18GA 1.5IN,NaN,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,101884,NDL HYPODERMC 18GA 1.5IN,NaN,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,1043,SOLN NS 0.9 PRCT 250ML,SOLN NACL IV 9% 250ML,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Create Pivot tables for Orders

In [7]:
#Concate the Par details
CHECK["Item_par"] = CHECK['ITEM'].astype(str)+"-"+ CHECK["LOCATION"].astype(str)

#Create Pivot table for PO usage
pivot_PO = PO1.pivot_table(index=['Deliver To ID','Item','UOM'], values=['Received QTY'], aggfunc='sum')

pivot_PO.head()

C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/4159983763.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CHECK["Item_par"] = CHECK['ITEM'].astype(str)+"-"+ CHECK["LOCATION"].astype(str)

                         Received QTY
Deliver To ID Item UOM
S5023         3    EA              38
              20   EA             110
              22   EA              81
              59   EA            1470
              60   EA             400

In [8]:
#Create index 
PO_USAGE = pivot_PO.reset_index()
PO_USAGE['Item'] = PO_USAGE['Item'].astype('int')
PO_USAGE["Conc1"] = PO_USAGE['Item'].astype(str)+"-"+ PO_USAGE["UOM"]
PO_USAGE["Item_par"] = PO_USAGE['Item'].astype(str)+"-"+ PO_USAGE["Deliver To ID"]
PO_USAGE.dtypes

Deliver To ID    object
Item              int32
UOM              object
Received QTY      int64
Conc1            object
Item_par         object
dtype: object

# Merge the Usage pivot and Lawson UOM with the Par form

In [9]:
#Merge the UC with the PO 
PO_USAGE1 = PO_USAGE.rename(columns={'Conc1': 'Item_UOM'})
#Change the Lawson UOM column to match 
UC1 = UC1.rename(columns={'Conc1_x': 'Item_UOM'})
#Merge the New PO form with the Lawson UOM
PO_AND_UC1=UC1.merge(PO_USAGE1, how='outer', on=['Item_UOM'])
PO_AND_UC=PO_AND_UC1.dropna(subset=['Item_par'])

# Drop the columns that Arent neccessary
PO_AND_UC2=PO_AND_UC1.drop(columns=['DESCRIPTION_x','Item_UOM','ALT-UOM-1'])

#merge the PO form with the Par form
Main_form = CHECK.merge(PO_AND_UC2, how='outer', on=['Item_par'])
Main_for=Main_form.dropna(subset=['Item_par'])
Main_for

,ENTITY,LOCATION,LOCATION NAME,ITEM_x,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,CLINICAL DESCRIPTION,REPL_FROM_CO,REPL_FROM_LOC,Item_par,ITEM_y,ALT-UOM-CONV-1,Deliver To ID,Item,UOM_y,Received QTY
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,NEEDLE BLOCK 17G,0.0,NaN,100010-S5023,NaN,NaN,NaN,NaN,NaN,NaN
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,NaN,0.0,NaN,100012-S5023,NaN,NaN,NaN,NaN,NaN,NaN
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,"COBAN 2""",0.0,NaN,100397-S5023,NaN,NaN,S5023,100397.0,EA,0.0
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,MEPITAC TAPE,0.0,NaN,101136-S5023,NaN,NaN,S5023,101136.0,BX,6.0
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,NEEDLE HYPO 27Gx0.5,0.0,NaN,101879-S5023,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,356448-S5023,NaN,NaN,S5023,356448.0,EA,112.0
207495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,356448-S5023,NaN,NaN,S5023,356448.0,RL,560.0
207496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,357256-S5023,NaN,NaN,S5023,357256.0,PK,300.0
207497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,358395-S5023,NaN,NaN,S5023,358395.0,CA,0.0
207498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,358705-S5023,NaN,NaN,S5023,358705.0,BX,5.0

In [10]:
#Replace NAN values with column values with items not on par
Main_for['LOCATION'] = Main_for['LOCATION'].fillna(Main_for['Deliver To ID'])
Main_for['UOM_x'] = Main_for['UOM_x'].fillna(Main_for['UOM_y'])
Main_for['Item ID'] = Main_for['ITEM_x'].fillna(Main_for['Item'])
Par = Par_Report[["LOCATION", "LOCATION NAME"]]
Main_form_1=Main_for.merge(Par, how='outer', on=['LOCATION'])


# shift column 'Name' to first position
first_column = Main_form_1.pop('LOCATION NAME_y')
  
# insert column using insert(position,column_name,
# first_column) function
Main_form_1.insert(3, 'LOCATION NAME_y', first_column)

Main1=Main_form_1.drop(columns=['LOCATION NAME_x'])
Main3=Main1.drop_duplicates(subset=['Item_par'])
Main=Main3.dropna(subset=['ITEM_x'])
Main

C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/3652419004.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_for['LOCATION'] = Main_for['LOCATION'].fillna(Main_for['Deliver To ID'])
C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/3652419004.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_for['UOM_x'] = Main_for['UOM_x'].fillna(Main_for['UOM_y'])
C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/3652419004.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_for['Item ID'] = Main_for['ITEM_x'].fillna(Main_for['Item'])

,ENTITY,LOCATION,LOCATION NAME_y,ITEM_x,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,REPL_FROM_CO,REPL_FROM_LOC,Item_par,ITEM_y,ALT-UOM-CONV-1,Deliver To ID,Item,UOM_y,Received QTY,Item ID
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,0.0,NaN,100010-S5023,NaN,NaN,NaN,NaN,NaN,NaN,100010.0
541,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,0.0,NaN,100012-S5023,NaN,NaN,NaN,NaN,NaN,NaN,100012.0
1082,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,0.0,NaN,100397-S5023,NaN,NaN,S5023,100397.0,EA,0.0,100397.0
1623,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,0.0,NaN,101136-S5023,NaN,NaN,S5023,101136.0,BX,6.0,101136.0
2164,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,0.0,NaN,101879-S5023,NaN,NaN,NaN,NaN,NaN,NaN,101879.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308911,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97389.0,ELCTRD ECG SQ RDLUCNT 24IN,2.0,PK,3.0,CARDINAL HEALTH,31424785,...,0.0,NaN,97389-S5023,NaN,NaN,NaN,NaN,NaN,NaN,97389.0
309452,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97737.0,TUBE TRCH TAPERGUARD EVAC SZ 7,10.0,EA,1.0,"COVIDIEN, LTD.",18870,...,0.0,NaN,97737-S5023,NaN,NaN,S5023,97737.0,EA,190.0,97737.0
309993,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97738.0,TUBE TRCHL TPR GARD 7.5MM,10.0,EA,1.0,"COVIDIEN, LTD.",18875,...,0.0,NaN,97738-S5023,NaN,NaN,S5023,97738.0,EA,290.0,97738.0
310534,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97739.0,TUBE TRCHL TPR GARD 8X11.8MM,10.0,EA,1.0,"COVIDIEN, LTD.",18880,...,0.0,NaN,97739-S5023,NaN,NaN,S5023,97739.0,EA,440.0,97739.0
311075,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97765.0,SET FLTRLN H HUMIDIFIED ADLT,3.0,EA,1.0,PHILIPS HEALTHCARE,989803105541,...,0.0,NaN,97765-S5023,NaN,NaN,NaN,NaN,NaN,NaN,97765.0

# Pivot tables for the INV orders

In [11]:
#Check the inventory types
INV_Check.dtypes

ICT-COMPANY               int64
ICC-NAME                 object
Currency Code            object
SORT-LITERAL            float64
FR-UPDATE-DATE          float64
                         ...
ICT-ADJIN-TOTAL-2       float64
ICT-ADJOUT-TOTAL-2      float64
ICT-TRANSFER-TOTAL-2    float64
ICT-PHY-INV-TOTAL-2     float64
ICT-REQ-RET-TOTAL-2     float64
Length: 66, dtype: object

In [12]:
#Create a Pivot table of the INV Orders
pivot_INV = INV_Check.pivot_table(index=['ICT-FROM-TO-LOC', 'ICT-ITEM','ICT-STOCK-UOM'], values=['ICT-QUANTITY'], aggfunc='sum')
pivot_INV

                                        ICT-QUANTITY
ICT-FROM-TO-LOC ICT-ITEM ICT-STOCK-UOM
S5023           20       EA                    -23.0
                718      EA                    -25.0
                798      SP                   -188.0
                943      EA                    -11.0
                951      EA                   -133.0
...                                              ...
                352199   EA                  -1800.0
                352522   EA                   -665.0
                352915   EA                     35.0
                353042   EA                    -56.0
                357313   EA                     -8.0

[90 rows x 1 columns]

In [13]:
#Convert the INV Pivot to a Dataframe

INVENTORY = pivot_INV.reset_index()
INVENTORY

   ICT-FROM-TO-LOC  ICT-ITEM ICT-STOCK-UOM  ICT-QUANTITY
0            S5023        20            EA         -23.0
1            S5023       718            EA         -25.0
2            S5023       798            SP        -188.0
3            S5023       943            EA         -11.0
4            S5023       951            EA        -133.0
..             ...       ...           ...           ...
85           S5023    352199            EA       -1800.0
86           S5023    352522            EA        -665.0
87           S5023    352915            EA          35.0
88           S5023    353042            EA         -56.0
89           S5023    357313            EA          -8.0

[90 rows x 4 columns]

In [14]:
#Find the absolute Value of the quantity of Inventory
INVENTORY['ICT-QUANTITY']= abs(INVENTORY['ICT-QUANTITY'])

In [15]:
#Check to see that the absolute value worked
INVENTORY.head()

  ICT-FROM-TO-LOC  ICT-ITEM ICT-STOCK-UOM  ICT-QUANTITY
0           S5023        20            EA          23.0
1           S5023       718            EA          25.0
2           S5023       798            SP         188.0
3           S5023       943            EA          11.0
4           S5023       951            EA         133.0

In [16]:
#Concatenate the item and Location in the pivot
INVENTORY["Item_par"] = INVENTORY['ICT-ITEM'].astype(str) +"-"+ INVENTORY["ICT-FROM-TO-LOC"].astype(str)
INVENTORY["Item_UOM"] = INVENTORY['ICT-ITEM'].astype(str) +"-"+ INVENTORY["ICT-STOCK-UOM"].astype(str)
INVENTORY.head()

  ICT-FROM-TO-LOC  ICT-ITEM ICT-STOCK-UOM  ICT-QUANTITY   Item_par Item_UOM
0           S5023        20            EA          23.0   20-S5023    20-EA
1           S5023       718            EA          25.0  718-S5023   718-EA
2           S5023       798            SP         188.0  798-S5023   798-SP
3           S5023       943            EA          11.0  943-S5023   943-EA
4           S5023       951            EA         133.0  951-S5023   951-EA

In [17]:
#merging the Lawson UOM Conversion with the Inventory and then 

#CHange the Data types to match
UC1 = UC1.rename(columns={'ITEM': 'ICT-ITEM'})
UC1 = UC1.rename(columns={'Conc': 'Item_UOM'})


INV_AND_UC1=UC1.merge(INVENTORY, how='outer', on=['Item_UOM'])


INV_AND_UC2=INV_AND_UC1.dropna(subset=['ICT-QUANTITY'])
INV_AND_UC2

,ICT-ITEM_x,DESCRIPTION_x,ALT-UOM-1,Item_UOM,ALT-UOM-CONV-1,ICT-FROM-TO-LOC,ICT-ITEM_y,ICT-STOCK-UOM,ICT-QUANTITY,Item_par
36,20.0,CATH ROBNEL 12FR,EA,20-EA,1.0,S5023,20.0,EA,23.0,20-S5023
1114,718.0,DEPRESSOR TONGUE STRL SR 6IN,EA,718-EA,1.0,S5023,718.0,EA,25.0,718-S5023
1238,798.0,CAP SYR TIP,SP,798-SP,1.0,S5023,798.0,SP,188.0,798-S5023
1312,943.0,TUBE ET 8.0 CUFFED HI-LO,EA,943-EA,1.0,S5023,943.0,EA,11.0,943-S5023
1335,951.0,BATTERY ALKALINE 1.5V AA,EA,951-EA,1.0,S5023,951.0,EA,133.0,951-S5023
...,...,...,...,...,...,...,...,...,...,...
201811,352199.0,3ML LUER LOCK SYRINGE TEAR ST,EA,352199-EA,1.0,S5023,352199.0,EA,1800.0,352199-S5023
202243,352522.0,TRNQT 1X18IN BLU TEXT RL AND,EA,352522-EA,1.0,S5023,352522.0,EA,665.0,352522-S5023
202912,352915.0,KIT CATH 19GA EPI NDL 17GA,EA,352915-EA,1.0,S5023,352915.0,EA,35.0,352915-S5023
203122,353042.0,LUMBAR CATHETER ACCESSORY KIT,EA,353042-EA,1.0,S5023,353042.0,EA,56.0,353042-S5023
206876,NaN,NaN,NaN,357313-EA,NaN,S5023,357313.0,EA,8.0,357313-S5023

# Merge the Main form with the INV form

In [18]:
#Merge the Inventory and PO forms
PO_INV1=Main.merge(INV_AND_UC2, how='left', on=['Item_par'])

#Drop Items that are not on the par
PO_INV1=PO_INV1.dropna(subset=['Item_par'])

PO_INV1.head()

,ENTITY,LOCATION,LOCATION NAME_y,ITEM_x,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,Item ID,ICT-ITEM_x,DESCRIPTION_x,ALT-UOM-1,Item_UOM,ALT-UOM-CONV-1_y,ICT-FROM-TO-LOC,ICT-ITEM_y,ICT-STOCK-UOM,ICT-QUANTITY
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,100010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,100012.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,100397.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,101136.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,101879.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Calculate the five and seven day par

In [19]:
#Import datetime to allow for conversion

PO1['PO Date']= PO1['PO Date']

#Find the Networkdays merge the orders and find the REC par for Medline Items
Date=PO1.loc[:,'PO Date']
Start_date =str( Date.iloc[1])
End_date =str( Date.iloc[-1])
PO_Date_Start1 = datetime.strptime(Start_date, '%Y-%m-%d')
PO_Date_Start=PO_Date_Start1.date()
PO_Date_End1 = datetime.strptime(End_date, '%Y-%m-%d')
PO_Date_End=PO_Date_End1.date()


days = np.busday_count(PO_Date_Start,PO_Date_End)
# Medline 5 day par calculation
Days=abs(days)/5
Days

24.8

In [20]:
#Import datetime to allow for conversion

PO1['PO Date']= PO1['PO Date']
#Find the Networkdays merge the orders and find the REC par fir DIRECT items
Date=PO1.loc[:,'PO Date']
Start_date =str( Date.iloc[1])
End_date =str( Date.iloc[-1])
PO_Date_Start1 = datetime.strptime(Start_date, '%Y-%m-%d')
PO_Date_Start=PO_Date_Start1.date()
PO_Date_End1 = datetime.strptime(End_date, '%Y-%m-%d')
PO_Date_End=PO_Date_End1.date()

#Direct 5 day par calculation
days = np.busday_count(PO_Date_Start,PO_Date_End)
Day_D=abs(days)/7
Day_D

17.714285714285715

In [21]:
#fill the Null values with an integer to make the formula work
PO_INV1['Received QTY'] = PO_INV1['Received QTY'].fillna(0)
PO_INV1['ICT-QUANTITY'] = PO_INV1['ICT-QUANTITY'].fillna(0)
PO_INV1['ALT-UOM-CONV-1_y'] = PO_INV1['ALT-UOM-CONV-1_y'].fillna(0)

In [22]:
PO_INV1.head()

,ENTITY,LOCATION,LOCATION NAME_y,ITEM_x,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,Item ID,ICT-ITEM_x,DESCRIPTION_x,ALT-UOM-1,Item_UOM,ALT-UOM-CONV-1_y,ICT-FROM-TO-LOC,ICT-ITEM_y,ICT-STOCK-UOM,ICT-QUANTITY
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,100010.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,100012.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,100397.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,101136.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,101879.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0

In [23]:
#Calculate REC par based on sourcing

#Calculate REC par for Medline
#if (PO_INV1['VENDOR'] == 13385).all():
    
   
       
if (PO_INV1['VENDOR'] == 13385).all() + (PO_INV1['ALT-UOM-CONV-1_y'] >= PO_INV1['ICT-QUANTITY']).any():
    PO_INV1["Combined"]= PO_INV1['Received QTY']+PO_INV1['ICT-QUANTITY']
elif (PO_INV1['VENDOR'] == 13385).all() + (PO_INV1['ALT-UOM-CONV-1_y'] < PO_INV1['ICT-QUANTITY']).any():
    PO_INV1["Combined"]=(PO_INV1['ICT-QUANTITY'] // PO_INV1['ALT-UOM-CONV-1_y'])+PO_INV1['ICT-QUANTITY']
PO_INV1["REC PAR"]=(PO_INV1['Combined'] / Days).apply(np.ceil)

PO_INV1.head()

,ENTITY,LOCATION,LOCATION NAME_y,ITEM_x,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,DESCRIPTION_x,ALT-UOM-1,Item_UOM,ALT-UOM-CONV-1_y,ICT-FROM-TO-LOC,ICT-ITEM_y,ICT-STOCK-UOM,ICT-QUANTITY,Combined,REC PAR
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,6.0,1.0
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0

In [24]:
#Find the difference between the Rec Par and the Par level
PO_INV1["DIFF of REC PAR"]=(PO_INV1['REC PAR'] - PO_INV1['PAR LEVEL'])

In [25]:
#Rec par for Direct Items


#if (PO_INV1['VENDOR'] != 13385.0).all():
#else:
if (PO_INV1['VENDOR'] != 13385.0).all() + (PO_INV1['ALT-UOM-CONV-1_y'] >= PO_INV1['ICT-QUANTITY']).all():
    PO_INV1["Combined"]= PO_INV1['Received QTY']+PO_INV1['ICT-QUANTITY']
elif (PO_INV1['VENDOR'] != 13385.0).all() + (PO_INV1['ALT-UOM-CONV-1_y'] < PO_INV1['ICT-QUANTITY']).all():
    PO_INV1["Combined"]=(PO_INV1['ICT-QUANTITY'] // PO_INV1['ALT-UOM-CONV-1_y'])+PO_INV1['ICT-QUANTITY']
PO_INV1["REC PAR Direct"]=(PO_INV1['Combined'] / Day_D).apply(np.ceil)
PO_INV1.head()

,ENTITY,LOCATION,LOCATION NAME_y,ITEM_x,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,Item_UOM,ALT-UOM-CONV-1_y,ICT-FROM-TO-LOC,ICT-ITEM_y,ICT-STOCK-UOM,ICT-QUANTITY,Combined,REC PAR,DIFF of REC PAR,REC PAR Direct
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,-20.0,0.0
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,-5.0,0.0
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,-2.0,0.0
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,NaN,0.0,NaN,NaN,NaN,0.0,6.0,1.0,-1.0,1.0
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,-1.0,0.0

In [26]:
#Keeping as testing
#calculate the Rec par 



#if (PO_INV1['ALT-UOM-CONV-1_y'] >= PO_INV1['ICT-QUANTITY']).any():
 #  PO_INV1["Combined"]= PO_INV1['Received QTY']+PO_INV1['ICT-QUANTITY']
#elif (PO_INV1['ALT-UOM-CONV-1_y'] < PO_INV1['ICT-QUANTITY']).any():
  #  PO_INV1["Combined"]=(PO_INV1['ICT-QUANTITY'] // PO_INV1['ALT-UOM-CONV-1_y'])+PO_INV1['ICT-QUANTITY']


#PO_INV1["REC PAR"]=(PO_INV1['Combined'] / Days).apply(np.ceil)

#PO_INV1.head()

In [27]:
#Find the difference between the Rec Par and the Par level
PO_INV1["DIFF of REC DIRECT PAR"]=(PO_INV1['REC PAR Direct'] - PO_INV1['PAR LEVEL'])

PO_INV1

,ENTITY,LOCATION,LOCATION NAME_y,ITEM_x,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,ALT-UOM-CONV-1_y,ICT-FROM-TO-LOC,ICT-ITEM_y,ICT-STOCK-UOM,ICT-QUANTITY,Combined,REC PAR,DIFF of REC PAR,REC PAR Direct,DIFF of REC DIRECT PAR
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,0.0,NaN,NaN,NaN,0.0,0.0,0.0,-20.0,0.0,-20.0
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,0.0,NaN,NaN,NaN,0.0,0.0,0.0,-5.0,0.0,-5.0
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,0.0,NaN,NaN,NaN,0.0,0.0,0.0,-2.0,0.0,-2.0
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,0.0,NaN,NaN,NaN,0.0,6.0,1.0,-1.0,1.0,-1.0
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,0.0,NaN,NaN,NaN,0.0,0.0,0.0,-1.0,0.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97389.0,ELCTRD ECG SQ RDLUCNT 24IN,2.0,PK,3.0,CARDINAL HEALTH,31424785,...,0.0,NaN,NaN,NaN,0.0,0.0,0.0,-2.0,0.0,-2.0
537,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97737.0,TUBE TRCH TAPERGUARD EVAC SZ 7,10.0,EA,1.0,"COVIDIEN, LTD.",18870,...,0.0,NaN,NaN,NaN,0.0,190.0,8.0,-2.0,11.0,1.0
538,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97738.0,TUBE TRCHL TPR GARD 7.5MM,10.0,EA,1.0,"COVIDIEN, LTD.",18875,...,0.0,NaN,NaN,NaN,0.0,290.0,12.0,2.0,17.0,7.0
539,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97739.0,TUBE TRCHL TPR GARD 8X11.8MM,10.0,EA,1.0,"COVIDIEN, LTD.",18880,...,0.0,NaN,NaN,NaN,0.0,440.0,18.0,8.0,25.0,15.0
540,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,97765.0,SET FLTRLN H HUMIDIFIED ADLT,3.0,EA,1.0,PHILIPS HEALTHCARE,989803105541,...,0.0,NaN,NaN,NaN,0.0,0.0,0.0,-3.0,0.0,-3.0

In [28]:
Cost.dtypes

ITEM                    int64
DESCRIPTION            object
MANUF_NBR              object
STOCK_UOM              object
Cost (STOCK UOM)      float64
BUY_UOM                object
BUY_UOM_CONVERSION    float64
Cost (BUY UOM)        float64
dtype: object

In [29]:
#add the Cost of the items from the PO form
PO_INV1 = PO_INV1.rename(columns={'ITEM_x': 'ITEM'})

Cost_item = Cost[["ITEM","STOCK_UOM","Cost (STOCK UOM)","BUY_UOM","Cost (BUY UOM)"]]
Cost_item["Stock-CONC"] = Cost_item['ITEM'].astype(str) +"-"+ Cost_item["STOCK_UOM"].astype(str)
Cost_item["BUY_CONC"] = Cost_item['ITEM'].astype(str) +"-"+ Cost_item["BUY_UOM"].astype(str)
Cost_item

C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/754884996.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Cost_item["Stock-CONC"] = Cost_item['ITEM'].astype(str) +"-"+ Cost_item["STOCK_UOM"].astype(str)
C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/754884996.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Cost_item["BUY_CONC"] = Cost_item['ITEM'].astype(str) +"-"+ Cost_item["BUY_UOM"].astype(str)

,ITEM,STOCK_UOM,Cost (STOCK UOM),BUY_UOM,Cost (BUY UOM),Stock-CONC,BUY_CONC
0,100,EA,2.455833,BX,88.410004,100-EA,100-BX
1,1000,EA,0.000000,EA,0.000000,1000-EA,1000-EA
2,10000,EA,1874.750000,EA,1874.750000,10000-EA,10000-EA
3,100000,EA,16.180000,CA,161.800003,100000-EA,100000-CA
4,100003,EA,4.000000,EA,4.000000,100003-EA,100003-EA
...,...,...,...,...,...,...,...
187991,99984,EA,19.860001,BX,198.600006,99984-EA,99984-BX
187992,99985,EA,13.750000,EA,13.750000,99985-EA,99985-EA
187993,99993,EA,17.070000,BX,170.699997,99993-EA,99993-BX
187994,99995,EA,27.440001,EA,27.440001,99995-EA,99995-EA
187995,99999,EA,10.450000,CA,104.500000,99999-EA,99999-CA

In [30]:
Cost_Buy = Cost_item[["BUY_CONC","Cost (BUY UOM)"]]
CB = Cost_Buy.rename(columns={'BUY_CONC': 'Item_UOM'})

Cost_Stock = Cost_item[["Stock-CONC","Cost (STOCK UOM)"]]
CS = Cost_Stock.rename(columns={'Stock-CONC': 'Item_UOM'})
CS

         Item_UOM  Cost (STOCK UOM)
0          100-EA          2.455833
1         1000-EA          0.000000
2        10000-EA       1874.750000
3       100000-EA         16.180000
4       100003-EA          4.000000
...           ...               ...
187991   99984-EA         19.860001
187992   99985-EA         13.750000
187993   99993-EA         17.070000
187994   99995-EA         27.440001
187995   99999-EA         10.450000

[187996 rows x 2 columns]

In [31]:
#add the cost of the item based off of Master Cost

BUY_PO=PO_INV1.merge(CB, how='outer', on=['Item_UOM'])
PO_INV2=BUY_PO.merge(CS, how='outer', on=['Item_UOM'])
Main9=PO_INV2.dropna(subset=['Item_par'])
Main9

,ENTITY,LOCATION,LOCATION NAME_y,ITEM,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,ICT-ITEM_y,ICT-STOCK-UOM,ICT-QUANTITY,Combined,REC PAR,DIFF of REC PAR,REC PAR Direct,DIFF of REC DIRECT PAR,Cost (BUY UOM),Cost (STOCK UOM)
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,NaN,NaN,0.0,0.0,0.0,-20.0,0.0,-20.0,NaN,NaN
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,NaN,NaN,0.0,0.0,0.0,-5.0,0.0,-5.0,NaN,NaN
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,NaN,NaN,0.0,0.0,0.0,-2.0,0.0,-2.0,NaN,NaN
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,NaN,NaN,0.0,6.0,1.0,-1.0,1.0,-1.0,NaN,NaN
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,NaN,NaN,0.0,0.0,0.0,-1.0,0.0,-1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,91858.0,ELCTRD ECG GEL SNAP ADLT,100.0,PK,5.0,3M HEALTHCARE,2670-5,...,91858.0,EA,1094.0,5858.0,237.0,137.0,331.0,231.0,NaN,0.103950
537,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,943.0,TUBE ET 8.0 CUFFED HI-LO,10.0,EA,1.0,"COVIDIEN, LTD.",86452,...,943.0,EA,11.0,181.0,8.0,-2.0,11.0,1.0,NaN,1.514000
538,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9445.0,GUARD TEETH,6.0,EA,1.0,TELEFLEX LLC,502276,...,9445.0,EA,30.0,54.0,3.0,-3.0,4.0,-2.0,NaN,5.993333
539,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,951.0,BATTERY ALKALINE 1.5V AA,3.0,BX,24.0,DURACELL USA,PC1500,...,951.0,EA,133.0,157.0,7.0,4.0,9.0,6.0,NaN,0.170000
540,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9588.0,NDL INTRAOSSEOUS 16 X 1-7/8,6.0,EA,1.0,CARDINAL HEALTH,8881245164,...,9588.0,EA,40.0,40.0,2.0,-4.0,3.0,-3.0,NaN,9.780000

In [32]:
PO_INV1.dtypes

ENTITY                     object
LOCATION                   object
LOCATION NAME_y            object
ITEM                      float64
ITEM DESCRIPTION           object
PAR LEVEL                 float64
UOM_x                      object
CONV UOM                  float64
MANUF NAME                 object
MANUF_NBR                  object
VENDOR                    float64
VENDOR CATALOG             object
COST CTR                  float64
Concat Lawson-CC           object
PREFER_BIN                 object
Division                   object
CLINICAL DESCRIPTION       object
REPL_FROM_CO              float64
REPL_FROM_LOC              object
Item_par                   object
ITEM_y                    float64
ALT-UOM-CONV-1_x          float64
Deliver To ID              object
Item                      float64
UOM_y                      object
Received QTY              float64
Item ID                   float64
ICT-ITEM_x                float64
DESCRIPTION_x              object
ALT-UOM-1                  object
Item_UOM                   object
ALT-UOM-CONV-1_y          float64
ICT-FROM-TO-LOC            object
ICT-ITEM_y                float64
ICT-STOCK-UOM              object
ICT-QUANTITY              float64
Combined                  float64
REC PAR                   float64
DIFF of REC PAR           float64
REC PAR Direct            float64
DIFF of REC DIRECT PAR    float64
dtype: object

In [33]:
Price = PO1[["Item","Unit Price"]]
Prices = Price.rename(columns={'Item': 'ITEM'})
PO_INV3=Main9.merge(Prices, how='outer', on=['ITEM'])
PO_INV4=PO_INV3.drop_duplicates(subset=['Item_par'])
PO_INV4

,ENTITY,LOCATION,LOCATION NAME_y,ITEM,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,ICT-STOCK-UOM,ICT-QUANTITY,Combined,REC PAR,DIFF of REC PAR,REC PAR Direct,DIFF of REC DIRECT PAR,Cost (BUY UOM),Cost (STOCK UOM),Unit Price
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,NaN,0.0,0.0,0.0,-20.0,0.0,-20.0,NaN,NaN,NaN
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,NaN,0.0,0.0,0.0,-5.0,0.0,-5.0,NaN,NaN,NaN
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,NaN,0.0,0.0,0.0,-2.0,0.0,-2.0,NaN,NaN,0.85
6,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,NaN,0.0,6.0,1.0,-1.0,1.0,-1.0,NaN,NaN,9.15
9,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,NaN,0.0,0.0,0.0,-1.0,0.0,-1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7627,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,943.0,TUBE ET 8.0 CUFFED HI-LO,10.0,EA,1.0,"COVIDIEN, LTD.",86452,...,EA,11.0,181.0,8.0,-2.0,11.0,1.0,NaN,1.514000,1.51
7642,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9445.0,GUARD TEETH,6.0,EA,1.0,TELEFLEX LLC,502276,...,EA,30.0,54.0,3.0,-3.0,4.0,-2.0,NaN,5.993333,11.99
7646,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,951.0,BATTERY ALKALINE 1.5V AA,3.0,BX,24.0,DURACELL USA,PC1500,...,EA,133.0,157.0,7.0,4.0,9.0,6.0,NaN,0.170000,4.08
7653,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9588.0,NDL INTRAOSSEOUS 16 X 1-7/8,6.0,EA,1.0,CARDINAL HEALTH,8881245164,...,EA,40.0,40.0,2.0,-4.0,3.0,-3.0,NaN,9.780000,NaN
7654,NaN,NaN,NaN,211671.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.34

In [34]:
INV_orders.dtypes

ICT-COMPANY               int64
ICC-NAME                 object
Currency Code            object
SORT-LITERAL            float64
FR-UPDATE-DATE          float64
                         ...
ICT-ADJIN-TOTAL-2       float64
ICT-ADJOUT-TOTAL-2      float64
ICT-TRANSFER-TOTAL-2    float64
ICT-PHY-INV-TOTAL-2     float64
ICT-REQ-RET-TOTAL-2     float64
Length: 66, dtype: object

In [35]:
INV_ors=INV_orders[["ICT-ITEM", "ICT-UNIT-COST"]]
INV_ors = INV_ors.rename(columns={'ICT-ITEM': 'ITEM'})
PO_INV1=PO_INV4.merge(INV_ors, how='outer', on=['ITEM'])
PO_INV=PO_INV1.drop_duplicates(subset=['Item_par'])
PO_INV

,ENTITY,LOCATION,LOCATION NAME_y,ITEM,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,ICT-QUANTITY,Combined,REC PAR,DIFF of REC PAR,REC PAR Direct,DIFF of REC DIRECT PAR,Cost (BUY UOM),Cost (STOCK UOM),Unit Price,ICT-UNIT-COST
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,0.0,0.0,0.0,-20.0,0.0,-20.0,NaN,NaN,NaN,NaN
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,0.0,0.0,0.0,-5.0,0.0,-5.0,NaN,NaN,NaN,NaN
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,0.0,0.0,0.0,-2.0,0.0,-2.0,NaN,NaN,0.85,NaN
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,0.0,6.0,1.0,-1.0,1.0,-1.0,NaN,NaN,9.15,NaN
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,0.0,0.0,0.0,-1.0,0.0,-1.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,943.0,TUBE ET 8.0 CUFFED HI-LO,10.0,EA,1.0,"COVIDIEN, LTD.",86452,...,11.0,181.0,8.0,-2.0,11.0,1.0,NaN,1.514000,1.51,1.6522
927,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9445.0,GUARD TEETH,6.0,EA,1.0,TELEFLEX LLC,502276,...,30.0,54.0,3.0,-3.0,4.0,-2.0,NaN,5.993333,11.99,6.2892
930,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,951.0,BATTERY ALKALINE 1.5V AA,3.0,BX,24.0,DURACELL USA,PC1500,...,133.0,157.0,7.0,4.0,9.0,6.0,NaN,0.170000,4.08,0.1855
931,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9588.0,NDL INTRAOSSEOUS 16 X 1-7/8,6.0,EA,1.0,CARDINAL HEALTH,8881245164,...,40.0,40.0,2.0,-4.0,3.0,-3.0,NaN,9.780000,NaN,10.6941
933,NaN,NaN,NaN,211671.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.34,NaN

In [36]:
PO_INV['Cost (BUY UOM)'] = PO_INV['Cost (BUY UOM)'].fillna(0)
PO_INV['Cost (STOCK UOM)'] = PO_INV['Cost (STOCK UOM)'].fillna(0)
PO_INV['Unit Price'] = PO_INV['Unit Price'].fillna(0)
PO_INV['ICT-UNIT-COST'] = PO_INV['ICT-UNIT-COST'].fillna(0)

PO_INV["Cost (BUY UOM)"] = PO_INV["Cost (BUY UOM)"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
PO_INV["Cost (STOCK UOM)"] = PO_INV["Cost (STOCK UOM)"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
PO_INV["Unit Price"] = PO_INV["Unit Price"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
PO_INV["ICT-UNIT-COST"] = PO_INV["ICT-UNIT-COST"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
PO_INV

C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/1353839663.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PO_INV['Cost (BUY UOM)'] = PO_INV['Cost (BUY UOM)'].fillna(0)
C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/1353839663.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PO_INV['Cost (STOCK UOM)'] = PO_INV['Cost (STOCK UOM)'].fillna(0)
C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/1353839663.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PO_INV['Unit Price'] = PO_INV['Unit Price'].fillna(0)
C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/1353839663.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PO_INV['ICT-UNIT-COST'] = PO_INV['ICT-UNIT-COST'].fillna(0)
C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/1353839663.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PO_INV["Cost (BUY UOM)"] = PO_INV["Cost (BUY UOM)"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/1353839663.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PO_INV["Cost (STOCK UOM)"] = PO_INV["Cost (STOCK UOM)"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/1353839663.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PO_INV["Unit Price"] = PO_INV["Unit Price"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))
C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/1353839663.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PO_INV["ICT-UNIT-COST"] = PO_INV["ICT-UNIT-COST"].apply(lambda x: format_currency(x, currency="USD", locale="en_US"))

,ENTITY,LOCATION,LOCATION NAME_y,ITEM,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,ICT-QUANTITY,Combined,REC PAR,DIFF of REC PAR,REC PAR Direct,DIFF of REC DIRECT PAR,Cost (BUY UOM),Cost (STOCK UOM),Unit Price,ICT-UNIT-COST
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,0.0,0.0,0.0,-20.0,0.0,-20.0,$0.00,$0.00,$0.00,$0.00
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,0.0,0.0,0.0,-5.0,0.0,-5.0,$0.00,$0.00,$0.00,$0.00
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,0.0,0.0,0.0,-2.0,0.0,-2.0,$0.00,$0.00,$0.85,$0.00
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,0.0,6.0,1.0,-1.0,1.0,-1.0,$0.00,$0.00,$9.15,$0.00
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,0.0,0.0,0.0,-1.0,0.0,-1.0,$0.00,$0.00,$0.00,$0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,943.0,TUBE ET 8.0 CUFFED HI-LO,10.0,EA,1.0,"COVIDIEN, LTD.",86452,...,11.0,181.0,8.0,-2.0,11.0,1.0,$0.00,$1.51,$1.51,$1.65
927,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9445.0,GUARD TEETH,6.0,EA,1.0,TELEFLEX LLC,502276,...,30.0,54.0,3.0,-3.0,4.0,-2.0,$0.00,$5.99,$11.99,$6.29
930,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,951.0,BATTERY ALKALINE 1.5V AA,3.0,BX,24.0,DURACELL USA,PC1500,...,133.0,157.0,7.0,4.0,9.0,6.0,$0.00,$0.17,$4.08,$0.19
931,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9588.0,NDL INTRAOSSEOUS 16 X 1-7/8,6.0,EA,1.0,CARDINAL HEALTH,8881245164,...,40.0,40.0,2.0,-4.0,3.0,-3.0,$0.00,$9.78,$0.00,$10.69
933,NaN,NaN,NaN,211671.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,$0.00,$0.00,$0.34,$0.00

# Start Dropping Columns

In [37]:
Par_R=PO_INV.drop(columns=['ITEM_y', 'ALT-UOM-CONV-1_x','Deliver To ID','UOM_y','Received QTY','ICT-ITEM_x','DESCRIPTION_x','ALT-UOM-1','ALT-UOM-CONV-1_y','ICT-FROM-TO-LOC','ICT-ITEM_y','ICT-STOCK-UOM','ICT-QUANTITY'])

In [38]:
Par_R

,ENTITY,LOCATION,LOCATION NAME_y,ITEM,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,Item_UOM,Combined,REC PAR,DIFF of REC PAR,REC PAR Direct,DIFF of REC DIRECT PAR,Cost (BUY UOM),Cost (STOCK UOM),Unit Price,ICT-UNIT-COST
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,NaN,0.0,0.0,-20.0,0.0,-20.0,$0.00,$0.00,$0.00,$0.00
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,NaN,0.0,0.0,-5.0,0.0,-5.0,$0.00,$0.00,$0.00,$0.00
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,NaN,0.0,0.0,-2.0,0.0,-2.0,$0.00,$0.00,$0.85,$0.00
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,NaN,6.0,1.0,-1.0,1.0,-1.0,$0.00,$0.00,$9.15,$0.00
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,NaN,0.0,0.0,-1.0,0.0,-1.0,$0.00,$0.00,$0.00,$0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
925,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,943.0,TUBE ET 8.0 CUFFED HI-LO,10.0,EA,1.0,"COVIDIEN, LTD.",86452,...,943-EA,181.0,8.0,-2.0,11.0,1.0,$0.00,$1.51,$1.51,$1.65
927,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9445.0,GUARD TEETH,6.0,EA,1.0,TELEFLEX LLC,502276,...,9445-EA,54.0,3.0,-3.0,4.0,-2.0,$0.00,$5.99,$11.99,$6.29
930,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,951.0,BATTERY ALKALINE 1.5V AA,3.0,BX,24.0,DURACELL USA,PC1500,...,951-EA,157.0,7.0,4.0,9.0,6.0,$0.00,$0.17,$4.08,$0.19
931,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9588.0,NDL INTRAOSSEOUS 16 X 1-7/8,6.0,EA,1.0,CARDINAL HEALTH,8881245164,...,9588-EA,40.0,2.0,-4.0,3.0,-3.0,$0.00,$9.78,$0.00,$10.69
933,NaN,NaN,NaN,211671.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,$0.00,$0.00,$0.34,$0.00

In [39]:

PO_INV1= Par_R.rename(columns={'Item ID': 'Item_lawson'})
MD2=MD[["ITEM","VEN-ITEM"]]
MD1= MD2.rename(columns={'ITEM': 'Item_lawson'})

MD1

       Item_lawson       VEN-ITEM
0              100     ETHVCP443H
1           100009       BAA18366
2           100010     HUDAB00050
3           100012     ARWAB00150
4           100016           Y520
...            ...            ...
11036        99876    KOLOCENT060
11037        99916  K-C0270162045
11038        99923        HTP3795
11039        99925        HTP3761
11040        99927       BXT4324A

[11041 rows x 2 columns]

In [40]:

Main_form=PO_INV1.merge(MD1, how='outer', on=['Item_lawson'])
Main_form

,ENTITY,LOCATION,LOCATION NAME_y,ITEM,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,Combined,REC PAR,DIFF of REC PAR,REC PAR Direct,DIFF of REC DIRECT PAR,Cost (BUY UOM),Cost (STOCK UOM),Unit Price,ICT-UNIT-COST,VEN-ITEM
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,0.0,0.0,-20.0,0.0,-20.0,$0.00,$0.00,$0.00,$0.00,HUDAB00050
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100012.0,NDL EPIDUR 17GA 15CM STIMUCATH,5.0,EA,1.0,TELEFLEX LLC,AB-00150,...,0.0,0.0,-5.0,0.0,-5.0,$0.00,$0.00,$0.00,$0.00,ARWAB00150
2,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100397.0,PACK COBAN LF WRAP BRIGHTS,2.0,EA,1.0,3M HEALTHCARE,2082C,...,0.0,0.0,-2.0,0.0,-2.0,$0.00,$0.00,$0.85,$0.00,MMM2082C
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101136.0,TAPE DRSG MEPITAC 118X.75IN,2.0,EA,1.0,MOLNLYCKE HEALTH CARE INC,298300,...,6.0,1.0,-1.0,1.0,-1.0,$0.00,$0.00,$9.15,$0.00,SCP298300
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,101879.0,NDLE HYPO 27GA 1/2IN STRL,1.0,BX,100.0,BECTON DICKINSON,305109,...,0.0,0.0,-1.0,0.0,-1.0,$0.00,$0.00,$0.00,$0.00,B-D305109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KOLOCENT060
11116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K-C0270162045
11117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTP3795
11118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTP3761
11119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BXT4324A

In [41]:
#Merge the MEdline SKU and par form, then merge the DED sheet 

Main_form1=Main_form.dropna(subset=['REC PAR'])
Main_form1 = Main_form1.rename(columns={'VEN-ITEM': 'Parent Item #'})

In [42]:
DED

,DED Account,Cust Item #,Parent Item #,Item,Item Desc,DED Qty,DED UM,Forecast Qty
0,C5604,3,SWD264945,SWD264945,"MBO-TUBE,SALEM SUMP,ARGYLE,14FR,48""",2.001,CS,2
1,C5604,5,B-D371110,B-D371110H,"BLADE,SURGICAL,CARBON-STEEL,10,STERILE",300.000,EA,197
2,C5604,6,B-D371111,B-D371111H,"BLADE,SURGICAL,CARBON-STEEL,11",169.000,EA,172
3,C5604,7,B-D371112,B-D371112BX,"BLADE,SURGICAL,CARBON-STEEL,12,STERILE",2.000,BX,1
4,C5604,8,B-D371115,B-D371115BX,"BLADE,SURGICAL,CARBON-STEEL,15",32.000,BX,11
...,...,...,...,...,...,...,...,...
6246,C5604,WWS9636H,WWS9636,WWS9636H,"CIRCUIT,EXPND,WYE,GAS,SAMP,2L",1018.000,EA,1452
6247,C5604,XOD40580H,XOD40580,XOD40580H,"KIT, POSITIONER, PATIENT, PINKPAD",2.000,EA,2
6248,1002266,NaN,DYNJA854618G,DYNJA854618G,854618 KIT GENERAL ANESTHESIA,16.001,CS,0
6249,C5605,NaN,K-C47117,K-C47117Z,"MBO-MASK,PROC,PLEATED,EARLOOPS,YELLOW",1630.000,BX,0
6250,1601309,NaN,SUT21715,SUT21715,LACERATION TRAY,5.000,CS,0

In [43]:
DED1=DED[["Parent Item #","DED UM","Forecast Qty"]]
DED1

     Parent Item # DED UM  Forecast Qty
0        SWD264945     CS             2
1        B-D371110     EA           197
2        B-D371111     EA           172
3        B-D371112     BX             1
4        B-D371115     BX            11
...            ...    ...           ...
6246       WWS9636     EA          1452
6247      XOD40580     EA             2
6248  DYNJA854618G     CS             0
6249      K-C47117     BX             0
6250      SUT21715     CS             0

[6251 rows x 3 columns]

In [44]:
#Concatenate the Medline SKU and the UOM
Main_form1["medline_conc"] = Main_form1['Parent Item #'].astype(str) +"-"+ Main_form1["UOM_x"].astype(str)
DED1["medline_conc"] = DED1['Parent Item #'].astype(str) +"-"+ DED1["DED UM"].astype(str)
Main_form2=Main_form1.merge(DED1, how='left', on=['medline_conc'])
Main_form3 = Main_form2.rename(columns={'Parent Item #_x': 'Parent Item #'})
Main_form4=Main_form3.merge(DED1, how='outer', on=['Parent Item #'])
#Main_form4=Main_form4.drop(['DESCRIPTION_y','ICT-ITEM_y','STATUS','VEN-ITEM-DESC','VENDOR','VPRI-UOM','DEFAULT-FLG','medline_conc_x','DED Account_x','Cust Item #_x','Parent Item #_y','Item_x','Item Desc_x','DED Qty_x','DED UM_x','DED Account_y','Cust Item #_y','Item_y','Item Desc_y','DED Qty_y','medline_conc_y'], axis=1)
Main_form5=Main_form4.dropna(subset=['REC PAR'])
#Print the par form so far
Main_sort=Main_form5.sort_values(by=['LOCATION'])
Main_sort

C:\Users\s0286524\AppData\Local\Temp/ipykernel_45788/1071589738.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DED1["medline_conc"] = DED1['Parent Item #'].astype(str) +"-"+ DED1["DED UM"].astype(str)

,ENTITY,LOCATION,LOCATION NAME_y,ITEM,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,Unit Price,ICT-UNIT-COST,Parent Item #,medline_conc_x,Parent Item #_y,DED UM_x,Forecast Qty_x,DED UM_y,Forecast Qty_y,medline_conc_y
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,$0.00,$0.00,HUDAB00050,HUDAB00050-EA,NaN,NaN,NaN,NaN,NaN,NaN
523,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,62.0,JELLY LUBE 2.7GR FOIL,2.0,BX,144.0,"MEDLINE INDUSTRIES, INC.",MDS032273,...,$50.66,$0.35,MDS032273Z,MDS032273Z-BX,MDS032273Z,BX,39.0,EA,28574.0,MDS032273Z-EA
524,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,62245.0,BLNKT SPECIALITY 60X36IN 8OZ,3.0,EA,1.0,3M HEALTHCARE,63000,...,$25.99,$0.00,AUG63000,AUG63000-EA,AUG63000,EA,5.0,EA,5.0,AUG63000-EA
525,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,629.0,ADPTR MULTI CNCTN 15X22MM,5.0,EA,1.0,TELEFLEX LLC,1422,...,$0.20,$0.00,HUD1422,HUD1422-EA,HUD1422,EA,551.0,EA,551.0,HUD1422-EA
526,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,629.0,ADPTR MULTI CNCTN 15X22MM,5.0,EA,1.0,TELEFLEX LLC,1422,...,$0.20,$0.00,HUD1422H,HUD1422H-EA,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,214217.0,SET FLUID WARM IRRIG,4.0,EA,1.0,ARIZANT HELAT CARE (WAS BAIR H,24750,...,$0.00,$0.00,AUG24750H,AUG24750H-EA,NaN,NaN,NaN,NaN,NaN,NaN
269,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,214374.0,FILTER TRANSFUSION BLOOD,6.0,EA,1.0,TERUMO MEDICAL CORPORATION,SQ40S,...,$12.94,$0.00,HZESQ40S,HZESQ40S-EA,HZESQ40S,EA,3.0,EA,3.0,HZESQ40S-EA
270,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,215381.0,SUCTION YANKAUER RIGID BULB,40.0,EA,1.0,"MEDLINE INDUSTRIES, INC.",DYND50130,...,$0.33,$0.00,DYND50130,DYND50130-EA,DYND50130,EA,4438.0,EA,4438.0,DYND50130-EA
272,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,215650.0,BLADE MAC 3 SINGLE-USE,1.0,PK,1.0,KARL STORZ ENDOSCOPY-AMERICA I,051113-10,...,$144.11,$0.00,KST5111310CS,KST5111310CS-PK,NaN,NaN,NaN,CS,11.0,KST5111310CS-CS
793,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9588.0,NDL INTRAOSSEOUS 16 X 1-7/8,6.0,EA,1.0,CARDINAL HEALTH,8881245164,...,$0.00,$10.69,SWD1245164,SWD1245164-EA,SWD1245164,EA,9.0,EA,9.0,SWD1245164-EA

Merge the ETA/ 90 Day and DISCO

In [45]:
#Merge the medline ETA with the main Par form
ETA
ETA1= ETA.rename(columns={'Customer Item #': 'ITEM'})
Main_ETA=Main_sort.merge(ETA1, how='outer', on=['ITEM'])
Main_ETA1=Main_ETA.dropna(subset=['REC PAR'])
Main_ETA=Main_ETA1.drop_duplicates(subset=['ITEM'])

In [46]:
Main_ETA

,ENTITY,LOCATION,LOCATION NAME_y,ITEM,ITEM DESCRIPTION,PAR LEVEL,UOM_x,CONV UOM,MANUF NAME,MANUF_NBR,...,ICT-UNIT-COST,Parent Item #,medline_conc_x,Parent Item #_y,DED UM_x,Forecast Qty_x,DED UM_y,Forecast Qty_y,medline_conc_y,Est Avail Date
0,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,100010.0,NDL EPIDUR 17GA 5CM STIMUCATH,20.0,EA,1.0,TELEFLEX LLC,AB-00050,...,$0.00,HUDAB00050,HUDAB00050-EA,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,62.0,JELLY LUBE 2.7GR FOIL,2.0,BX,144.0,"MEDLINE INDUSTRIES, INC.",MDS032273,...,$0.35,MDS032273Z,MDS032273Z-BX,MDS032273Z,BX,39.0,EA,28574.0,MDS032273Z-EA,NaT
3,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,62245.0,BLNKT SPECIALITY 60X36IN 8OZ,3.0,EA,1.0,3M HEALTHCARE,63000,...,$0.00,AUG63000,AUG63000-EA,AUG63000,EA,5.0,EA,5.0,AUG63000-EA,2022-10-05
4,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,629.0,ADPTR MULTI CNCTN 15X22MM,5.0,EA,1.0,TELEFLEX LLC,1422,...,$0.00,HUD1422,HUD1422-EA,HUD1422,EA,551.0,EA,551.0,HUD1422-EA,NaT
6,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,64.0,TUBE SALEM SUMP 18FR,8.0,EA,1.0,CARDINAL HEALTH,8888264986,...,$0.00,SWD264986,SWD264986-EA,SWD264986,EA,858.0,EA,858.0,SWD264986-EA,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,214217.0,SET FLUID WARM IRRIG,4.0,EA,1.0,ARIZANT HELAT CARE (WAS BAIR H,24750,...,$0.00,AUG24750,AUG24750-EA,AUG24750,EA,0.0,EA,0.0,AUG24750-EA,NaT
790,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,214374.0,FILTER TRANSFUSION BLOOD,6.0,EA,1.0,TERUMO MEDICAL CORPORATION,SQ40S,...,$0.00,HZESQ40S,HZESQ40S-EA,HZESQ40S,EA,3.0,EA,3.0,HZESQ40S-EA,NaT
791,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,215381.0,SUCTION YANKAUER RIGID BULB,40.0,EA,1.0,"MEDLINE INDUSTRIES, INC.",DYND50130,...,$0.00,DYND50130,DYND50130-EA,DYND50130,EA,4438.0,EA,4438.0,DYND50130-EA,NaT
792,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,215650.0,BLADE MAC 3 SINGLE-USE,1.0,PK,1.0,KARL STORZ ENDOSCOPY-AMERICA I,051113-10,...,$0.00,KST5111310CS,KST5111310CS-PK,NaN,NaN,NaN,CS,11.0,KST5111310CS-CS,NaT
793,SHC,S5023,PS_500P 2F_K251_ANES KB S5023,9588.0,NDL INTRAOSSEOUS 16 X 1-7/8,6.0,EA,1.0,CARDINAL HEALTH,8881245164,...,$10.69,SWD1245164,SWD1245164-EA,SWD1245164,EA,9.0,EA,9.0,SWD1245164-EA,NaT

In [47]:
#filter the par form for locations and Cost Center
#CHECK = Par_Report[(Par_Report["Par Location ID"]=="S1037")|(Par_Report["Par Location ID"]=="S1038")|(Par_Report["Par Location ID"]=="S2432")|(Par_Report["Par Location ID"]=="S2434")|(Par_Report["Par Location ID"]=="S2433")|(Par_Report["Par Location ID"]=="S2574")|(Par_Report["Par Location ID"]=="S0806")|(Par_Report["Par Location ID"]=="S0807")|(Par_Report["Par Location ID"]=="S0808")|(Par_Report["Par Location ID"]=="S0864")]

INV_Walk=INV_orders[(INV_orders["ICT-FROM-TO-LOC"]=="W1005")|(INV_orders["ICT-FROM-TO-LOC"]=="W8005")]
INV_Walk

,ICT-COMPANY,ICC-NAME,Currency Code,SORT-LITERAL,FR-UPDATE-DATE,TO-UPDATE-DATE,ICT-ITEM,ITE-DESCRIPTION,ITE-DESCRIPTION2,ICT-LOCATION,...,TO-UPDATE-DATE-2,ICT-LOCATION-2,ICL-NAME-2,ICT-RECEIPT-TOTAL-2,ICT-ISSUE-TOTAL-2,ICT-ADJIN-TOTAL-2,ICT-ADJOUT-TOTAL-2,ICT-TRANSFER-TOTAL-2,ICT-PHY-INV-TOTAL-2,ICT-REQ-RET-TOTAL-2
11,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,1044,SOLN VISIV D5W 500ML BAG,CONTNR SOLN IV D 500ML 5%,8005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,1047,SOLN IV 10% D INJCTN PRNTRL 1L,SOLN IV D10 W 1000ML BAG,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,1050,SOLN VISIV NS.9 PRCT 500 ML BA,IV SOL NACL 0.9% 500ML,8005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,1051,SOLN VIS IV D5W 250ML BAG,IV SOL D5 250ML,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,1051,SOLN VIS IV D5W 250ML BAG,IV SOL D5 250ML,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,84669,MASK N95 3-FOLD 1870PLUS,N95 - LG,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
660,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,84669,MASK N95 3-FOLD 1870PLUS,N95 - LG,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
670,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,91858,ELCTRD ECG GEL SNAP ADLT,ELECTRODE 3M RED DOT CS OF 200,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
671,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,91858,ELCTRD ECG GEL SNAP ADLT,ELECTRODE 3M RED DOT CS OF 200,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
673,1,STANFORD HOSPITAL AND CLINICS,USD,NaN,NaN,NaN,9206,SEAL TAMPER PROOF TIE RED NUMB,SEAL NUMBRD RED PULL-TITE II,1005,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
#Walkups
INV_orders
#Create a Pivot table of the INV Orders
pivot_Walk = INV_Walk.pivot_table(index=['ICT-FROM-TO-LOC','ICT-OFF-ACCT-UNIT', 'ICT-ITEM',], values=['ICT-QUANTITY'], aggfunc='count')
pivot_Walk

                                            ICT-QUANTITY
ICT-FROM-TO-LOC ICT-OFF-ACCT-UNIT ICT-ITEM
W1005           74501.0           62                   2
                                  677                  1
                                  702                  1
                                  1047                 1
                                  1051                 2
...                                                  ...
W8005           74501.0           1050                 1
                                  7312                 1
                                  343392               1
                                  343482               1
                                  343791               1

[74 rows x 1 columns]

In [49]:
#Convert the INV Pivot to a Dataframe

INVENTORY_1 = pivot_Walk.reset_index()
INVENTORY_1

   ICT-FROM-TO-LOC  ICT-OFF-ACCT-UNIT  ICT-ITEM  ICT-QUANTITY
0            W1005            74501.0        62             2
1            W1005            74501.0       677             1
2            W1005            74501.0       702             1
3            W1005            74501.0      1047             1
4            W1005            74501.0      1051             2
..             ...                ...       ...           ...
69           W8005            74501.0      1050             1
70           W8005            74501.0      7312             1
71           W8005            74501.0    343392             1
72           W8005            74501.0    343482             1
73           W8005            74501.0    343791             1

[74 rows x 4 columns]

In [50]:
CHECK_2 = CHECK[["COST CTR", "Concat Lawson-CC"]]
CHECK_3 = Par_Report[["ITEM", "ITEM DESCRIPTION"]]
CHECK_1=CHECK_2.rename(columns={"COST CTR":'Cost Ctr'})
CHECK_1

        Cost Ctr Concat Lawson-CC
131131   74501.0     100010-74501
131132   74501.0     100012-74501
131133   74501.0     100397-74501
131134   74501.0     101136-74501
131135   74501.0     101879-74501
...          ...              ...
131667   74501.0      97389-74501
131668   74501.0      97737-74501
131669   74501.0      97738-74501
131670   74501.0      97739-74501
131671   74501.0      97765-74501

[541 rows x 2 columns]

In [51]:
#Merge the Inventory with
IV=INVENTORY_1.rename(columns={'ICT-OFF-ACCT-UNIT':'Cost Ctr'})
Walkup=CHECK_1.merge(IV, how='outer', on=['Cost Ctr'])

Walku=Walkup.rename(columns={"ICT-ITEM":'ITEM'})
Walkups=Walku.merge(CHECK_3, how='outer', on=['ITEM'])
Walkups["Conc"]= Walkups['ITEM']+Walkups['Cost Ctr']
WALK=Walkups.drop_duplicates(subset=['Conc'])
WALK

,Cost Ctr,Concat Lawson-CC,ICT-FROM-TO-LOC,ITEM,ICT-QUANTITY,ITEM DESCRIPTION,Conc
0,74501.0,100010-74501,W1005,62,2.0,JELLY LUBE 2.7GR FOIL,74563.0
167169,74501.0,100010-74501,W1005,677,1.0,SCSR SURGCL 5.5IN,75178.0
305124,74501.0,100010-74501,W1005,702,1.0,PAPER EXAM TABLE 21INX225FT,75203.0
372749,74501.0,100010-74501,W1005,1047,1.0,SOLN IV 10% D INJCTN PRNTRL 1L,75548.0
400340,74501.0,100010-74501,W1005,1051,2.0,SOLN VIS IV D5W 250ML BAG,75552.0
...,...,...,...,...,...,...,...
3670144,74501.0,100010-74501,W1005,352522,1.0,TRNQT 1X18IN BLU TEXT RL AND,427023.0
3670685,74501.0,100010-74501,W1005,352915,1.0,KIT CATH 19GA EPI NDL 17GA,427416.0
3671226,74501.0,100010-74501,W8005,1044,1.0,SOLN VISIV D5W 500ML BAG,75545.0
3708014,74501.0,100010-74501,W8005,1050,1.0,SOLN VISIV NS.9 PRCT 500 ML BA,75551.0
3838395,NaN,NaN,NaN,222840,NaN,APPLICATOR SKIN CLOSURE .6ML 3,NaN

In [52]:

CHECK_1.to_excel(File_name1)

In [53]:

ExcelWorkbook = load_workbook(File_name1)
writer = pd.ExcelWriter(File_name1, engine = 'openpyxl')
writer.book = ExcelWorkbook
WALK.to_excel(writer, sheet_name = 'Walkups', index=False)
Main_sort.to_excel(writer, sheet_name = 'Par Form', index=False)
writer.save()
writer.close()

In [54]:
ExcelWorkbook.close()
writer.book.close()